name: Auto Reset Firestore
on:
  push:
    branches:
      - main
jobs:
  Auto Reset Firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: creat json file
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'secret_file.json'
        env: 
          type: ${{ secrets.TYPE }},
          project_id: ${{ secrets.PROJECT_ID }},
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }},
          private_key: ${{ secrets.PRIVATE_KEY }},
          client_email: ${{ secrets.CLIENT_EMAIL }},
          client_id: ${{ secrets.CLIENT_ID }},
          auth_uri: ${{ secrets.AUTH_URL }},
          token_uri: ${{ secrets.TOKEN_URL }},
          auth_provider_x509_cert_url: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }},
          client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }},
          universe_domain: ${{ secrets.UNIVERSE_DOMAIN }}

      - name: Run Python
        run: python test.py #名前変更